### PR TITLE
Do not vendor six

### PR DESCRIPTION
**Pull request by hugovk**
For #162.

Instead install the latest.

Includes #179 (drop Py2.6).

### CODE REVIEW

**Comment by hugovk** [comment]
Note: Python 3 is also failing on latest master: https://travis-ci.org/hugovk/paver/builds/294374716

**Comment by adiroiban** [comment]
This removes six vendoring, but also drops support for python 2.6 and 2.5.

Is paver still active? I have not seen any commit in master in more than 1 years

**Comment by hugovk** [comment]
Yes, it also drops Python 2.6 and 2.5. See https://github.com/paver/paver/issues/162 for Paver 1.3 plans.

And @Almad is still around (eg. https://github.com/paver/paver/issues/165#issuecomment-334494701) so I guess he'll merge things :)

**Comment by Almad** [comment]
I am around, just having less time to do active dev work since I am now mostly working in other languages during day time :( Also—happy to add more contributors if someone is interested.

So let's get it green and let the merges flow.

**Comment by adiroiban** [comment]
I can help with review and testing the patched.

I agree that tests should be green.

Maybe start with a separate PR which first fixed the tests on master... or fix the test in this PR.

Do we need to support older python 3 version?

I was thinking that python 3.5 should be enough and should make keeping python 2 and 3 support easier.

**Comment by hugovk** [comment]
I'd suggest to get things green in a separate PR, unless the changes are trivial. 

https://github.com/paver/paver/issues/162 has install stats: 3.4 has 4.8%. I think at least 3.2 and 3.3 can go, both are EOL and little used.

**Comment by Almad** [comment]
@hugovk could you please rebase on top of master? After that, it should be green and ready to go 💪

**Comment by hugovk** [comment]
@Almad Rebased!

**Comment by adiroiban** [comment]
Looks good. Thanks!

I assume that this is based on hugovk:rm-2.6 so #179 should be merged first... as otherwise this will merge those changes

**Comment by jzoldak** [comment]
@hugovk thank you for figuring out this fix.

@Almad thank you for this module, we have been using paver for task automation for our project. Could you please release a new version with this fix?

**Comment by Almad** [comment]
@jzoldak Working on it! Apologies for delay, but want to get #163 done to speed up the process for the future to get the releases back on track.

**Comment by Almad** [comment]
Your thoughts on #195 would be welcome.

**Comment by jzoldak** [comment]
@Almad tyvm for the release. And thanks again for all the awesome code.

**Comment by Almad** [comment]
@jzoldak no problem, happy to help :)

**Pull request merged**
