### PR TITLE
Drop support for Python 2.6

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/paver/paver/issues/162.

### CODE REVIEW

**Comment by hugovk** [comment]
Note: Python 3 is also failing on latest master: https://travis-ci.org/hugovk/paver/builds/294374716

**Comment by Almad** [comment]
The Python3 failure is weird, will try to look into it.

The reason for keeping python 2.6- was jython, quite a few people were using Paver for automation on JVM and I don't see any 2.7 being released...however I agree it's becoming so desparately out of date that it'll be better to drop it.

**Comment by Almad** [comment]
Right, it _is_ released now...note to self: do not oss in the night.

OK, let's fix master and get this one out.

**Comment by adiroiban** [comment]
This looks good. Thanks!

Why not also drop Python 3.2 and 3.3  as they should also be EOL ?

Last release for 3.2 is Oct 2014 https://www.python.org/downloads/release/python-326/ and 3.2 was retired

3.3 was retired in Sep 2017 https://www.python.org/downloads/release/python-337/

**Comment by Almad** [comment]
I did that for 3.2 in https://github.com/paver/paver/pull/185 , it's true that maybe we can do that for 3.4 as well.

**Comment by hugovk** [comment]
Remove 3.3 and 3.4, or just 3.3?

**Pull request merged**
